---
title: "Partial positivity simulation"
format: pdf
editor: visual
---

```{r}
## Set-up
library(dplyr)
devtools::load_all()
```

## Simulation settings

```{r}
set <- purrr::pmap_dfr(
  .l = settings,
  .f = ~settings_tbl(data.frame(...))
) |>
  tidyr::pivot_wider(id_cols = c(effect, name), names_from = pos_type, values_from = value)

set |>
    kableExtra::kable(format = "latex", 
                      escape = FALSE,
                      col.names = c(" ", " "), 
                      booktabs = T, 
                      align = c("lr")) |>
    kableExtra::kable_styling(position = "center", 
                              latex_options = "HOLD_position")
```
## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
